[project]
name = "simple-test-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dask>=2025.3.0",
    "mlflow>=2.21.3",
    "ray>=2.44.1",
    "torch>=2.6.0",
]
